services:
  - type: web
    name: nexus-bot
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DISCORD_TOKEN
        sync: false
      - key: OWNER_ID
        sync: false
      - key: TOPGG_TOKEN
        sync: false
      - key: DISCORDBOTLIST_TOKEN
        sync: false
      - key: VOIDBOTS_TOKEN
        sync: false
      - key: CLIENT_SECRET
        sync: false
      - key: CLIENT_ID
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: ADMIN_WEBHOOK_URL
        sync: false
    autoDeploy: true

